### ISSUE TITLE
Gasnade uses timers, needs replace with CurTime

### ISSUE THREAD

**Issue by TrenchFroast** [hexahedronic/basewars#27]
please erradicate this

**Comment by Tenrys** [comment]
Reference code?

**Comment by TrenchFroast** [comment]
what do you mean reference code

**Comment by TrenchFroast** [comment]
one week later still not done
i am unhappy
and dont start at me to do it because i cba

**Comment by polivilas** [comment]
1 month later and still not done @TrenchFroast

**Comment by TrenchFroast** [comment]
@polivilas its ur fault u nub

**Comment by polivilas** [comment]
how about i fix it now @TrenchFroast

**Comment by CaveeJohnson** [comment]
Do it then.

**Comment by polivilas** [comment]
done
